# Jekyll Theme Notiva Configuration
# ----------------------------------------------------------------------
# Visit the GitHub page for detailed documentation: https://github.com/songano/jekyll-theme-notiva

# [CUSTOMIZABLE] Site Settings
# ----------------------------------------------------------------------
title: Notiva                   # Site title
tagline: A Developer-Friendly Blog Theme  # Site tagline
description: >-                 # Site description (shown in search engines)
  Notiva is a modern, feature-rich Jekyll theme designed for developers
  who want to create impressive technical blogs with minimal effort.
url: ""                         # Site base hostname & protocol (e.g., https://example.com)
baseurl: ""                     # Sub-path of your site, e.g. /blog
repository: username/repo-name  # GitHub username/repo-name for the site
avatar: /assets/images/avatar.jpg  # Your avatar image path
lang: en                        # Primary language (en, ko-KR, zh-CN, etc.)
timezone: Asia/Seoul            # Your timezone (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

# [CUSTOMIZABLE] Author Information
# ----------------------------------------------------------------------
author:
  name: Your Name
  bio: >-
    Software Developer specializing in web technologies.
    Passionate about open source and sharing knowledge.
  location: Seoul, Korea
  email: your.email@example.com
  links:
    - label: GitHub
      icon: github
      url: https://github.com/username
    - label: Twitter
      icon: twitter
      url: https://twitter.com/username
    - label: LinkedIn
      icon: linkedin
      url: https://linkedin.com/in/username

# [CUSTOMIZABLE] Theme Settings
# ----------------------------------------------------------------------
theme_settings:
  # Color scheme: dark, light, or auto (system preference)
  color_scheme: auto

  # Avatar shape (circle, rounded, square)
  avatar_shape: rounded
  
  # Layout settings
  sidebar_position: left        # Position of sidebar (left or right)
  sidebar_collapsed: false      # Whether sidebar is collapsed by default on mobile
  
  # Post settings
  show_post_thumbnail: true     # Show post thumbnails in listings
  show_post_date: true          # Show post date in listings
  show_post_categories: true    # Show post categories in listings
  show_post_tags: true          # Show post tags in listings
  show_reading_time: true       # Show estimated reading time for posts
  show_post_modified_date: true # Show last modified date on posts
  
  # Display settings
  post_layout_style: grid       # Post listing style (grid or list)
  toc_enabled: true             # Enable table of contents by default
  toc_floating: true            # Enable floating TOC for posts
  
  # Home page settings
  home_posts_limit: 10          # Number of posts to show on home page
  show_trending_tags: true      # Show trending tags section
  show_popular_posts: true      # Show popular posts section
  pinned_posts_enabled: true    # Enable pinned posts feature
  
  # Comments system (uncomment to enable)
  # comments_provider: disqus     # Options: disqus, giscus, utterances
  # disqus_shortname: your-disqus-shortname
  # giscus_repo: username/repo
  # giscus_repo_id: your-repo-id
  # giscus_category: Announcements
  # giscus_category_id: your-category-id
  # utterances_repo: username/repo

# [CUSTOMIZABLE] PWA Settings
# ----------------------------------------------------------------------
pwa:
  enable: true                            # Enable Progressive Web App features
  cache_version: 1                        # Increment when making changes to force cache refresh
  manifest:
    name: "Notiva"                        # Web App name
    short_name: "Notiva"                  # Web App short name
    description: "A Jekyll theme"         # Web App description
    theme_color: "#121021"                # Theme color for browser
    background_color: "#121021"           # Background color for splash screen
    display: "standalone"                 # Display mode
    start_url: "/?utm_source=homescreen"  # Start URL when launched from home screen
    icons:
      - src: "/assets/images/icons/pwa-192x192.png"
        sizes: "192x192"
        type: "image/png"
      - src: "/assets/images/icons/pwa-512x512.png"
        sizes: "512x512"
        type: "image/png"

# [CUSTOMIZABLE] Site Verification Settings
# ----------------------------------------------------------------------
# These verification codes are used to verify ownership of your site
# for various search engines and webmaster tools
webmaster_verifications:
  google: "google-site-verification-code" # Replace with your verification code
  bing:                                 # Replace with your verification code
  yandex:                             # Replace with your verification code
  naver:                               # Replace with your verification code
  baidu:                               # Replace with your verification code

# [CUSTOMIZABLE] Analytics Settings
# ----------------------------------------------------------------------
# Google Analytics
# Replace UA-XXXXXXXX-X with your Google Analytics tracking ID
# or use gtag format G-XXXXXXXXXX
google_analytics: G-XXXXXXXXXX

# Firebase (for visitor statistics)
# IMPORTANT: Don't put your actual Firebase config here, use GitHub Actions secrets instead
# These are just placeholders that will be replaced during the build process
firebase:
  enabled: true
  # For actual deployment, set these as GitHub Actions secrets and refer to them as:
  # api_key: ${{ secrets.FIREBASE_API_KEY }}
  # auth_domain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  # project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
  # storage_bucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  # messaging_sender_id: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  # app_id: ${{ secrets.FIREBASE_APP_ID }}
  # measurement_id: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

# [CUSTOMIZABLE] Sharing & SEO Settings
# ----------------------------------------------------------------------
# Allow overriding of default OG/Twitter cards for each post
sharing:
  twitter:
    username: "@username"        # Twitter username (without @)
  facebook:
    app_id:                      # Facebook App ID
    publisher:                   # Facebook Page URL
  og_default_image: /assets/images/og-default.jpg  # Default OG image

# [CUSTOMIZABLE] Code Highlighting Settings
# ----------------------------------------------------------------------
code_highlight:
  enabled: true
  show_line_numbers: true        # Show line numbers in code blocks
  show_title: true               # Show file name in code blocks
  default_theme: github-dark     # Default theme (github-dark, github-light, etc.)

# [CUSTOMIZABLE] Math & Diagram Settings
# ----------------------------------------------------------------------
math:
  enabled: true                  # Enable math rendering (KaTeX)
  auto_render: false             # Auto-render all math (can impact performance)

mermaid:
  enabled: true                  # Enable Mermaid diagrams

# [CUSTOMIZABLE] Build Settings
# ----------------------------------------------------------------------
permalink: /posts/:title/
paginate: 10
paginate_path: /page/:num/
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: plaintext
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# [NOT CUSTOMIZABLE] Required plugins - DO NOT REMOVE these plugins
# ----------------------------------------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from

# [CUSTOMIZABLE] Archives Configuration
# ----------------------------------------------------------------------
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: archive
    month: archive
    category: archive
    tag: archive
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    category: '/categories/:name/'
    tag: '/tags/:name/'

# [NOT CUSTOMIZABLE] Compression Settings
# ----------------------------------------------------------------------
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# [NOT CUSTOMIZABLE] Sass conversion settings
# Note: Notiva theme uses Tailwind CSS instead of Sass/SCSS.
# This setting is only included for Jekyll's internal compatibility.
# ----------------------------------------------------------------------
sass:
  sass_dir: _sass
  style: compressed

# [NOT CUSTOMIZABLE] Exclude Files/Folders
# ----------------------------------------------------------------------
exclude:
  - node_modules
  - '*.gem'
  - '*.gemspec'
  - 'package*.json'
  - '*.config.mjs'
  - .git
  - .github
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .vscode
  - '*-lock.yaml'
  - _app/
  - tsconfig.json