# Notiva Jekyll Theme
# Author: Your Name
# Version: 1.0.0
# Homepage: https://github.com/songano/jekyll-theme-notiva
# License: MIT
#
# IMPORTANT: When modifying _config.yml, you must stop and restart 
# the Jekyll server for changes to take effect.
# ---------------------------------------------------------------------

# ---------------------------------------------------------------
# CONFIG GUIDE:
# [CUSTOMIZABLE] - Settings you can safely modify to personalize your site
# [NOT CUSTOMIZABLE] - Settings I recommend not to modify unless you have a thorough
#                    understanding of Jekyll and this theme's architecture
# ---------------------------------------------------------------


# ---------------------------------------------------------------
# [CUSTOMIZABLE] Theme Settings
# ---------------------------------------------------------------
theme: jekyll-theme-notiva

# Site Settings
# ----------------------------------------------------------------------
title: Notiva                         # Site title
tagline: A modern Jekyll theme        # Site tagline
description: >-                       # Site description (used for SEO)
  Notiva is a modern, developer-friendly Jekyll theme for tech blogs.
url: ""                               # Site base URL (e.g., https://username.github.io)
baseurl: ""                           # Subpath (e.g., /blog)
avatar: /assets/images/avatar.jpg     # Path to your avatar image
favicon: /assets/images/favicon.ico   # Path to your favicon
locale: en                            # Site Locale (e.g., en, Ko-KR, zh-CN...)
timezone: Asia/Seoul                  # Timezone (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

# User Info
# ----------------------------------------------------------------------
author:
  name: Your Name                     # Your name
  bio: >-                             # Your bio
    Developer, writer, and open source enthusiast.
    Passionate about web technologies and technical writing.
  email: your.email@example.com       # Your email
  

# Social Links
# Use full URLs. Leave blank to hide.
# ----------------------------------------------------------------------
social:
  github: https://github.com/username
  twitter: https://twitter.com/username
  linkedin: https://linkedin.com/in/username
  stackoverflow: 
  facebook: 
  instagram: 
  youtube: 
  discord: 
  telegram: 
  medium: 
  dev: 
  rss: true                           # Set to true to enable RSS feed

# Social Links Display
# ----------------------------------------------------------------------
social_display:
  position: both                   # Where to display social links: [sidebar|footer|both]

# Theme Appearance
# ----------------------------------------------------------------------
appearance:
  theme_mode: auto                    # [light|dark] - Default theme mode
  code_highlight: true                # Enable syntax highlighting
  code_copy: true                     # Enable code copy button
  animated: true                      # Enable animations
  back_to_top: true                   # Enable back to top button
  toc_enabled: true                   # Enable table of contents
  toc_collapsed: true                 # Collapse TOC by default
  sidebar_position: left              # Sidebar position [left|right]
  display_mode: list                  # How to display posts on home [grid|list]
  avatar_shape: rounded               # [circle|rounded] - Avatar shape
  # mouse_tracker: true                 # Mouse Tracker by default

# [CUSTOMIZABLE] Post Settings
# ----------------------------------------------------------------------
post:
  related_posts_count: 5              # Number of related posts to display
  recent_posts_count: 5               # Number of recent posts to display
  show_date: true                     # Show post date
  show_categories: true               # Show post categories
  show_tags: true                     # Show post tags
  show_comments: true                 # Show comments
  show_author: true                   # Show post author
  show_reading_time: true             # Show estimated reading time
  reading_time_wpm: 200               # Words per minute for reading time calculation
  excerpt_length: 200                 # Length of post excerpts
  permalink: /:year/:month/:day/:title/  # Post URL format


# [CUSTOMIZABLE] PWA Settings
# ----------------------------------------------------------------------
pwa:
  enable: true                        # Enable Progressive Web App features
  cache_version: 1                    # Increment when making changes to force cache refresh
  manifest:
    name: "Notiva"                    # Web App name
    short_name: "Notiva"              # Web App short name
    description: "A Jekyll theme"     # Web App description
    theme_color: "#121021"            # Theme color for browser
    background_color: "#121021"       # Background color for splash screen
    display: "standalone"             # Display mode
    start_url: "/?utm_source=homescreen"  # Start URL when launched from home screen
    icons:
      - src: "/assets/images/icons/pwa-192x192.png"
        sizes: "192x192"
        type: "image/png"
      - src: "/assets/images/icons/pwa-512x512.png"
        sizes: "512x512"
        type: "image/png"

# [CUSTOMIZABLE] Analytics Settings
# ----------------------------------------------------------------------
analytics:
  google:
    id:                               # Google Analytics ID (e.g., UA-XXXXXXXX-X or G-XXXXXXXXXX)
  firebase:
    # For Firebase configurations, it's recommended to use GitHub Actions secrets
    # instead of putting these values directly in _config.yml
    # See GitHub repository wiki for setup instructions
    enable: true                     # Enable Firebase analytics and visitor counting
    api_key: ""                       # Firebase API Key (use GitHub Actions secrets)
    auth_domain: ""                   # Firebase Auth domain (use GitHub Actions secrets)
    project_id: ""                    # Firebase project ID (use GitHub Actions secrets)
    storage_bucket: ""                # Firebase storage bucket (use GitHub Actions secrets)
    messaging_sender_id: ""           # Firebase messaging sender ID (use GitHub Actions secrets)
    app_id: ""                        # Firebase app ID (use GitHub Actions secrets)
    measurement_id: ""                # Firebase measurement ID (use GitHub Actions secrets)

# [CUSTOMIZABLE] Comments Settings
# ----------------------------------------------------------------------
comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider:                           # [disqus|utterances|giscus]
  # The provider options are as follows:
  disqus:
    shortname:                        # Fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:                             # <gh-username>/<repo>
    issue_term:                       # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:                             # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:                          # optional, default to 'pathname'
    strict:                           # optional, default to '0'
    input_position:                   # optional, default to 'bottom'
    lang:                             # optional, default to the value of `site.lang`
    reactions_enabled:                # optional, default to the value of `1`

# [CUSTOMIZABLE] Site Verification Settings
# ----------------------------------------------------------------------
# For more documentation, see: https://github.com/jekyll/jekyll-seo-tag
webmaster_verifications:
  google:                             # Google verification code
  bing:                               # Bing verification code
  alexa:                              # Alexa verification code
  yandex:                             # Yandex verification code
  baidu:                              # Baidu verification code
  facebook:                           # Facebook verification code


# [CUSTOMIZABLE] Additional Feature Settings
# ----------------------------------------------------------------------
features:
  math: true                          # Enable math expressions (KaTeX)
  mermaid: true                       # Enable Mermaid diagrams
  image_zoom: true                    # Enable image zoom on click
  site_search: true                   # Enable site search
  show_visitor_stats: true            # Show visitor statistics (requires Firebase)
  scroll_progress: true               # Show scroll progress
  image_lazyload: true                # Enable image lazy loading

# [CUSTOMIZABLE] Pagination Settings
# ----------------------------------------------------------------------
# 아카이브 페이지네이션 설정
archive_pagination:
  enabled: true
  per_page: 4  # 기본 페이지당 포스트 수
  layouts:  # 페이지네이션을 적용할 레이아웃
    - tag
    - category
    - year
    - month

# pagination:
#   enabled: true
#   per_page: 10           # 페이지당 포스트 수
#   permalink: '/page/:num/'
#   title: ':title - 페이지 :num'

# autopages:
#   enabled: true
#   categories:
#     enabled: false  # 카테고리 비활성화
#   collections:
#     enabled: false  # 컬렉션 비활성화
#   tags:
#     layouts:
#       - 'tag.html'
#     title: ':tag'
#     permalink: '/tags/:tag/'

# [NOT CUSTOMIZABLE] Build Settings
# ----------------------------------------------------------------------
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: plaintext
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# [NOT CUSTOMIZABLE] Jekyll Archives Configuration
# ----------------------------------------------------------------------
# For more documentation, see: https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
    year: archive
    month: archive
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"
    month: "/archives/:year/:month/"

# [NOT CUSTOMIZABLE] Collections Settings
# ----------------------------------------------------------------------
# Collections are a Jekyll feature for grouping related content.
# The navigation collection manages the main menu items in the sidebar.
collections:
  navigation:
    output: true
    sort_by: order

# [NOT CUSTOMIZABLE] Default Front Matter Settings
# ----------------------------------------------------------------------
# IMPORTANT: Please read carefully before making changes!
# This section defines default values for different content types.
# Incorrect changes here can affect your entire site's behavior.
# If you're not fully familiar with Jekyll's defaults system,
# please refer to: https://jekyllrb.com/docs/configuration/front-matter-defaults/
# or keep modifications minimal to avoid unexpected issues.
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: navigation # see `site.collections`
    values:
      layout: page
      permalink: /:title/


# [NOT CUSTOMIZABLE] Compression Settings
# ----------------------------------------------------------------------
compress_html:
  clippings: all
  comments: all
  endings: all
  # ignore:
  #   envs: [development]
  blanklines: false
  profile: false

# Required plugins - DO NOT REMOVE these plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from


# [NOT CUSTOMIZABLE] Files and Paths to Exclude from build
# ----------------------------------------------------------------------
exclude:
  - node_modules
  - "*.gem"
  - "*.gemspec"
  - "package*.json"
  - "*.config.mjs"
  - .git
  - .github
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .vscode
  - "*-lock.yaml"
  - _scripts/
  - _styles/
  - _app/
  - tsconfig.json
  - vite.config.ts